# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXImageDown' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXImageDown
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'

  target 'RXImageDownTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
