# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXAnimation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXAnimation
	pod 'RxSwift'
	pod 'RxCocoa'
	
  target 'RXAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
