# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'boxing_sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for boxing_sample
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 4.0'
  pod 'RxDataSources'

end
